### PR TITLE
[WIP] - Remove token param

### PR DESCRIPTION
**Pull request by jontours**

### CODE REVIEW

**Comment by rogeruiz** [comment]
hey @jontours is this pipeline flown with these changes? Since we neither have a private repo we're pulling `in` from or pushing releases `out` to a repo, we should be safe to remove this. but I wanna verify if it's working already.

**Comment by rogeruiz** [comment]
We may want to keep this, @jontours. Consider the note at the top of the `readme`:

> If you're seeing rate limits affecting you then please add a token to the source configuration. This will increase your number of allowed requests.

**Comment by jontours** [comment]
We can replace the token as the old one was expired.  I'll work on this, the build is broken anyway with `dep ensure` not able to pull oath2 for some reason.

**Comment by bengerman13** [comment]
@jontours should we close this PR?

**Pull request closed without merging**
